apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blue-green-applicationset
  namespace: argocd
spec:
  generators:
  # List generator for blue-green environments
  - list:
      elements:
      - environment: blue
        version: "1.0.0"
        replicas: "3"
        port: "8080"
        active: "true"
      - environment: green
        version: "2.0.0" 
        replicas: "3"
        port: "80"
        active: "false"
  template:
    metadata:
      name: 'flask-{{environment}}-app'
      labels:
        environment: '{{environment}}'
        version: '{{version}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/edenmor/blue-green-deployment.git
        targetRevision: HEAD
        path: k8s-applicationset/{{environment}}
        helm:
          parameters:
          - name: image.tag
            value: '{{version}}'
          - name: replicaCount
            value: '{{replicas}}'
          - name: service.port
            value: '{{port}}'
          - name: environment.name
            value: '{{environment}}'
          - name: environment.active
            value: '{{active}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: flask-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
