# Default values for flask-green-app
replicaCount: 3

image:
  repository: flask-app
  pullPolicy: Never
  tag: "2.0.0"

environment:
  name: "green"
  active: false

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
